[workspace]
resolver = "2"
members = ["crates/yune", "crates/yune-runtime", "crates/yune-render", "crates/yune-reference", "crates/yune-physics"]
default-members = ["crates/yune"]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/cobebriant4556/Yune"

[workspace.dependencies]
anyhow = "1.0"
base64 = "0.22"
async-io = "2.4"
font8x8 = "0.3"
fontdue = "0.9"
glam = "0.33"
image = { version = "0.25.10", default-features = false, features = ["png"] }
mlua = { version = "0.11.6", features = ["luau"] }
mlua-luau-scheduler = { path = "upstream/lune/crates/mlua-luau-scheduler" }
rbx_dom_weak = "4.0"
rbx_mesh = { version = "0.8.0", default-features = false, features = ["mesh", "mesh-v1"] }
rapier3d = "0.35.3"
lune = { path = "upstream/lune/crates/lune" }
lune-roblox = { path = "upstream/lune/crates/lune-roblox" }
lune-std-task = { path = "upstream/lune/crates/lune-std-task" }
yune-runtime = { path = "crates/yune-runtime" }
yune-reference = { path = "crates/yune-reference" }
yune-physics = { path = "crates/yune-physics" }
yune-render = { path = "crates/yune-render" }

[workspace.lints.clippy]
all = { level = "deny", priority = -3 }
cargo = { level = "warn", priority = -2 }
pedantic = { level = "warn", priority = -1 }

cast_lossless = { level = "allow", priority = 1 }
cast_possible_truncation = { level = "allow", priority = 1 }
cast_possible_wrap = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
cast_sign_loss = { level = "allow", priority = 1 }

similar_names = { level = "allow", priority = 1 }
unnecessary_wraps = { level = "allow", priority = 1 }
unnested_or_patterns = { level = "allow", priority = 1 }
unreadable_literal = { level = "allow", priority = 1 }

multiple_crate_versions = { level = "allow", priority = 1 }
module_inception = { level = "allow", priority = 1 }
needless_pass_by_value = { level = "allow", priority = 1 }
wildcard_imports = { level = "allow", priority = 1 }
