[workspace]
resolver = "2"
members = ["crates/yune", "crates/yune-render"]
default-members = ["crates/yune"]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/cobebriant4556/Yune"

[workspace.dependencies]
anyhow = "1.0"
async-io = "2.4"
font8x8 = "0.3"
glam = "0.33"
image = { version = "0.25.10", default-features = false, features = ["png"] }
mlua = { version = "0.11.6", features = ["luau"] }
rbx_dom_weak = "4.0"
lune = { git = "https://github.com/lune-org/lune", rev = "d96087b46e8c3b751a50f6e80ca099e1008e7e33" }
lune-roblox = { git = "https://github.com/lune-org/lune", rev = "d96087b46e8c3b751a50f6e80ca099e1008e7e33" }
yune-render = { path = "crates/yune-render" }
