[workspace]
resolver = "2"
members = ["crates/yune", "crates/yune-runtime", "crates/yune-render"]
default-members = ["crates/yune"]

[workspace.package]
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/cobebriant4556/Yune"

[workspace.dependencies]
anyhow = "1.0"
async-io = "2.4"
font8x8 = "0.3"
glam = "0.33"
image = { version = "0.25.10", default-features = false, features = ["png"] }
mlua = { version = "0.11.6", features = ["luau"] }
rbx_dom_weak = "4.0"
lune = { path = "upstream/lune/crates/lune" }
lune-roblox = { path = "upstream/lune/crates/lune-roblox" }
yune-runtime = { path = "crates/yune-runtime" }
yune-render = { path = "crates/yune-render" }
